version: '3'

services:
  db:
    container_name: 'auth_container'
    image: mysql:8
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
